version: '3'

services:
    web:
        build:
            context: .
            args:
                - JFROG_USERNAME
                - JFROG_PASSWORD
        depends_on:
            - db
        ports:
            - '3000:3000'
        volumes:
            - .:/var/app
    db:
        image: postgres:9.6.2-alpine
        expose:
            - 5432
        volumes:
            - postgres96:/var/lib/postgresql/data
volumes:
    postgres96: